title: Encrypt-Decrypt
description: Simple text encryption and decryption.
logo: /assets/images/logo_128.png
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
github:
  is_project_page: false
plugins:
  - jekyll-relative-links
